# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: native-open-edl
# label used for menu selection
label: Native-EDL
description: Adds EDL entries for open source feeds that have a format natively compatable with PANOS

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - EDL

# ---------------------------------------------------------------------
# end of preamble section


# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: native-edl
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
    file: native-edl.xml
# ---------------------------------------------------------------------
# end of snippets section